/* Diary calendar, CRUD, and encrypted attachment storage. */
let diaryView='month', diaryDate=todayISO(), diaryTag='';
const localDate=value=>{const [y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d,12);};
const dateISO=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const addDays=(value,n)=>{const d=localDate(value);d.setDate(d.getDate()+n);return dateISO(d);};
const longDate=value=>localDate(value).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});
const normalizeTags=values=>{const seen=new Set();return values.map(x=>String(x).trim()).filter(x=>{const key=x.toLocaleLowerCase();if(!key||seen.has(key))return false;seen.add(key);return true;});};
function getDiaryEventsForDate(date,tag=diaryTag){
  const events=[];
  state.entries.filter(e=>e.status==='completed'&&e.date===date).forEach(e=>events.push({type:'session',id:e.id,date,title:sessionLabel(e.sessionType),subtitle:e.scripture||'',href:`#entry/${e.id}`}));
  state.prayers.filter(p=>p.createdDate===date).forEach(p=>events.push({type:'prayer',id:p.id,date,title:p.memberName||'Prayer request',subtitle:p.text||'',href:`#prayer/${p.id}`}));
  state.diaryEntries.filter(d=>d.date===date&&(!tag||(d.tags||[]).some(t=>t.toLocaleLowerCase()===tag.toLocaleLowerCase()))).forEach(d=>events.push({type:'diary',id:d.id,date,title:d.title||'Diary entry',subtitle:d.body||'',href:`#diary/entry/${d.id}`}));
  return events;
}
function diaryEvent(e,compact=false){return `<a class="diary-event ${e.type}" href="${e.href}"><span class="event-type">${e.type==='session'?'☷ Session':e.type==='prayer'?'♡ Prayer':'✎ Diary'}</span><strong>${esc(e.title)}</strong>${!compact&&e.subtitle?`<span>${esc(e.subtitle).slice(0,100)}</span>`:''}</a>`;}
function diaryHeader(){const tags=[...new Set(state.diaryEntries.flatMap(d=>d.tags||[]).map(t=>t.trim()).filter(Boolean))].sort();return `<div class="section-title diary-title"><div><div class="eyebrow">Personal history</div><h1>Diary</h1></div><a class="btn primary" href="#diary/new/${diaryDate}">＋ New Entry</a></div><div class="calendar-controls card flat"><button class="icon-btn" data-diary-move="-1" aria-label="Previous ${esc(diaryView)}">‹</button><strong>${diaryView==='day'?longDate(diaryDate):localDate(diaryDate).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</strong><button class="icon-btn" data-diary-move="1" aria-label="Next ${esc(diaryView)}">›</button><button class="btn small secondary" data-diary-today>Today</button></div><div class="view-tabs" role="group" aria-label="Calendar view">${[['day','Day'],['week','7 Days'],['month','Month']].map(([v,l])=>`<button class="btn small ${diaryView===v?'primary':'ghost'}" data-diary-view="${v}" aria-pressed="${diaryView===v}">${l}</button>`).join('')}</div>${tags.length?`<div class="tag-filters" aria-label="Filter diary entries by tag"><button class="pill ${!diaryTag?'selected':''}" data-diary-tag="">All diary</button>${tags.map(t=>`<button class="pill ${diaryTag===t?'selected':''}" data-diary-tag="${esc(t)}">${esc(t)}</button>`).join('')}</div>`:''}`;}
function dayContent(date){const events=getDiaryEventsForDate(date),groups=['session','prayer','diary'];return `<section class="day-agenda"><div class="section-title"><h2>${longDate(date)}</h2><a class="btn small secondary" href="#diary/new/${date}">New Diary Entry</a></div>${groups.map(type=>{const list=events.filter(e=>e.type===type);return list?list.length?`<section class="event-section"><h3>${type==='session'?'Sessions':type==='prayer'?'Prayers':'Diary'}</h3><div class="list">${list.map(e=>diaryEvent(e)).join('')}</div></section>`:'' : '';}).join('')}${events.length?'':'<div class="empty">Nothing recorded for this day yet.</div>'}</section>`;}
function weekContent(){const d=localDate(diaryDate);d.setDate(d.getDate()-d.getDay());return `<div class="week-agenda">${Array.from({length:7},(_,i)=>{const date=addDays(dateISO(d),i),events=getDiaryEventsForDate(date);return `<section class="card flat week-day"><button class="day-link" data-diary-day="${date}"><strong>${longDate(date)}</strong></button>${events.length?events.map(e=>diaryEvent(e,true)).join(''):'<span class="subtle mini">No events</span>'}</section>`;}).join('')}</div>`;}
function monthContent(){const d=localDate(diaryDate),year=d.getFullYear(),month=d.getMonth(),first=new Date(year,month,1,12),days=new Date(year,month+1,0,12).getDate(),lead=first.getDay();return `<div class="month-calendar"><div class="weekday-row">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<span>${x}</span>`).join('')}</div><div class="month-grid">${'<span class="month-blank"></span>'.repeat(lead)}${Array.from({length:days},(_,i)=>{const date=dateISO(new Date(year,month,i+1,12)),events=getDiaryEventsForDate(date),counts=events.reduce((a,e)=>(a[e.type]=(a[e.type]||0)+1,a),{});return `<button class="month-day ${date===todayISO()?'today':''} ${date===diaryDate?'selected':''}" data-diary-day="${date}" aria-label="${longDate(date)}, ${events.length} events"><strong>${i+1}</strong><span>${counts.diary?`✎ ${counts.diary}`:''}</span><span>${counts.session?`☷ ${counts.session}`:''}</span><span>${counts.prayer?`♡ ${counts.prayer}`:''}</span></button>`;}).join('')}</div></div>`;}
function diaryPage(){return shell(`<div class="page">${diaryHeader()}${diaryView==='day'?dayContent(diaryDate):diaryView==='week'?weekContent():monthContent()}</div>`,'diary');}
function diaryEditor(id,date){const item=state.diaryEntries.find(d=>d.id===id),value=item||{date:date||todayISO(),title:'',body:'',tags:[],media:[]};return shell(`<div class="page"><div class="hero"><div class="eyebrow">${item?'Edit':'New'} diary entry</div><h1>${item?'Edit entry':'What do you want to remember?'}</h1></div><form class="card form" id="diaryForm" data-id="${item?.id||''}"><div class="field"><label for="diaryEntryDate">Date</label><input class="input" id="diaryEntryDate" type="date" required value="${esc(value.date)}"></div><div class="field"><label for="diaryTitle">Title <span class="subtle">(optional)</span></label><input class="input" id="diaryTitle" placeholder="Entry title" value="${esc(value.title)}"></div><div class="field"><label for="diaryBody">Entry</label><textarea class="textarea diary-textarea" id="diaryBody" placeholder="What happened today? What do you want to remember?">${esc(value.body)}</textarea><small>Markdown is rendered after saving.</small></div><div class="field"><label for="diaryTags">Tags <span class="subtle">(comma separated)</span></label><input class="input" id="diaryTags" value="${esc((value.tags||[]).join(', '))}" placeholder="Gratitude, Family"></div><div class="field"><label for="diaryMedia">Photos and video</label><input class="input" id="diaryMedia" type="file" accept="image/*,video/*" multiple><small>Attachments are encrypted and kept on this device. Available browser storage limits file size.</small></div><div id="existingMedia" class="attachment-editor">${(value.media||[]).map(m=>`<label class="attachment-row"><input type="checkbox" data-remove-media="${m.id}"> Remove <span>${esc(m.name)} · ${formatBytes(m.size)}</span></label>`).join('')}</div><div id="diaryError" class="warning" role="alert"></div><div class="form-actions"><a class="btn ghost" href="${item?`#diary/entry/${item.id}`:'#diary'}">Cancel</a><button class="btn primary" type="submit">Save Entry</button></div></form></div>`,'diary');}
function diaryDetail(id){const d=state.diaryEntries.find(x=>x.id===id);if(!d)return diaryPage();return shell(`<div class="page"><div class="section-title"><div><div class="eyebrow">${longDate(d.date)}</div><h1>${esc(d.title||'Diary entry')}</h1></div><a class="btn small secondary" href="#diary/entry/${d.id}/edit">Edit</a></div><article class="card flat"><div class="detail-body markdown-body">${renderMarkdown(d.body)}</div>${(d.tags||[]).length?`<div class="tag-list">${d.tags.map(t=>`<span class="pill">${esc(t)}</span>`).join('')}</div>`:''}<div class="media-gallery" id="diaryMediaView"></div><div class="meta">Created ${new Date(d.createdAt).toLocaleString()}${d.updatedAt!==d.createdAt?` · Updated ${new Date(d.updatedAt).toLocaleString()}`:''}</div></article><button class="btn danger section" data-delete-diary="${d.id}">Delete entry</button></div>`,'diary');}
function formatBytes(n){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`;}
async function mediaStore(mode='readonly'){const db=await openDB();return db.transaction(MEDIA_STORE,mode).objectStore(MEDIA_STORE);}
async function putDiaryMedia(id,file){if(!cryptoSession.dek)throw new Error('Gathered is locked');const iv=randomBytes(12),bytes=await file.arrayBuffer(),ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:encoder.encode(id)},cryptoSession.dek,bytes),store=await mediaStore('readwrite');return new Promise((resolve,reject)=>{const req=store.put({id,iv:b64(iv),ciphertext:b64(ciphertext)},id);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error);});}
async function getDiaryMedia(id,mime){const store=await mediaStore(),record=await new Promise((resolve,reject)=>{const req=store.get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});if(!record)throw new Error('Attachment is missing');const bytes=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(record.iv),additionalData:encoder.encode(id)},cryptoSession.dek,unb64(record.ciphertext));return new Blob([bytes],{type:mime});}
async function deleteDiaryMedia(id){const store=await mediaStore('readwrite');return new Promise((resolve,reject)=>{const req=store.delete(id);req.onsuccess=resolve;req.onerror=()=>reject(req.error);});}
async function exportDiaryMedia(){const store=await mediaStore();return new Promise((resolve,reject)=>{const req=store.getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function replaceDiaryMedia(records=[]){const store=await mediaStore('readwrite');await new Promise((resolve,reject)=>{const req=store.clear();req.onsuccess=resolve;req.onerror=()=>reject(req.error);});await importDiaryMedia(records);}
async function importDiaryMedia(records=[]){const store=await mediaStore('readwrite');return Promise.all(records.map(record=>new Promise((resolve,reject)=>{const req=store.put(record,record.id);req.onsuccess=resolve;req.onerror=()=>reject(req.error);})))}
let diaryObjectUrls=[];
function releaseDiaryObjectUrls(){diaryObjectUrls.forEach(URL.revokeObjectURL);diaryObjectUrls=[];}
async function hydrateDiaryMedia(entry){const host=document.getElementById('diaryMediaView');releaseDiaryObjectUrls();if(!host)return;for(const media of entry.media||[]){try{const blob=await getDiaryMedia(media.id,media.mimeType),url=URL.createObjectURL(blob);diaryObjectUrls.push(url);host.insertAdjacentHTML('beforeend',media.type==='image'?`<a href="${url}" target="_blank" rel="noopener"><img src="${url}" alt="Attached image: ${esc(media.name)}"></a>`:`<video src="${url}" controls preload="metadata" aria-label="Attached video: ${esc(media.name)}"></video>`);}catch{host.insertAdjacentHTML('beforeend',`<div class="warning">${esc(media.name)} could not be decrypted or is missing.</div>`);}}}
window.addEventListener('hashchange',releaseDiaryObjectUrls);
function bindDiaryEditor(){const form=document.getElementById('diaryForm');if(!form)return;form.onsubmit=async e=>{e.preventDefault();const old=state.diaryEntries.find(d=>d.id===form.dataset.id),input=document.getElementById('diaryMedia'),files=[...input.files],body=document.getElementById('diaryBody').value,title=document.getElementById('diaryTitle').value.trim(),removed=[...form.querySelectorAll('[data-remove-media]:checked')].map(x=>x.dataset.removeMedia);if(!body.trim()&&!files.length&&!(old?.media||[]).some(m=>!removed.includes(m.id))){document.getElementById('diaryError').textContent='Write something or attach a photo or video before saving.';return;}const button=form.querySelector('button[type="submit"]'),added=[],previousEntries=state.diaryEntries;button.disabled=true;input.disabled=true;try{for(let index=0;index<files.length;index++){const file=files[index];if(!/^image\//.test(file.type)&&!/^video\//.test(file.type))throw new Error(`${file.name} is not a supported image or video.`);const isImage=file.type.startsWith('image/'),id=uid('media');let stored=file,width,height,mimeType=file.type;if(isImage){button.textContent=files.filter(item=>item.type.startsWith('image/')).length>1?'Preparing photos…':'Preparing photo…';const prepared=await GatheredDiaryImage.prepareDiaryImage(file);stored=prepared.blob;width=prepared.width;height=prepared.height;mimeType=prepared.mimeType;}button.textContent='Encrypting…';await putDiaryMedia(id,stored);added.push({id,type:isImage?'image':'video',mimeType,name:file.name,size:stored.size,...(isImage?{width,height}:{}),createdAt:new Date().toISOString()});if(index<files.length-1)await new Promise(resolve=>setTimeout(resolve,0));}const now=new Date().toISOString(),entry={id:old?.id||uid('diary'),date:document.getElementById('diaryEntryDate').value,title,body,tags:normalizeTags(document.getElementById('diaryTags').value.split(',')),media:[...(old?.media||[]).filter(m=>!removed.includes(m.id)),...added],createdAt:old?.createdAt||now,updatedAt:now};state.diaryEntries=old?previousEntries.map(d=>d.id===old.id?entry:d):[...previousEntries,entry];await saveState();await Promise.all(removed.map(deleteDiaryMedia));location.hash=`#diary/entry/${entry.id}`;render();toast('Diary entry saved');}catch(error){state.diaryEntries=previousEntries;await Promise.all(added.map(m=>deleteDiaryMedia(m.id).catch(()=>{})));document.getElementById('diaryError').textContent=error?.name==='QuotaExceededError'?'This device does not have enough storage for those attachments. Your existing entry is unchanged.':`Could not save attachments. ${error.message||'Your existing entry is unchanged.'}`;button.disabled=false;input.disabled=false;button.textContent='Save Entry';}};}
function renderDiaryRoute(parts){if(parts[1]==='new'){document.getElementById('app').innerHTML=diaryEditor('new',parts[2]);bindDiaryEditor();}else if(parts[1]==='entry'){if(parts[3]==='edit'){document.getElementById('app').innerHTML=diaryEditor(parts[2]);bindDiaryEditor();}else{document.getElementById('app').innerHTML=diaryDetail(parts[2]);const d=state.diaryEntries.find(x=>x.id===parts[2]);if(d)void hydrateDiaryMedia(d);}}else document.getElementById('app').innerHTML=diaryPage();}
document.addEventListener('click',async e=>{const view=e.target.closest('[data-diary-view]');if(view){diaryView=view.dataset.diaryView;render();return;}const day=e.target.closest('[data-diary-day]');if(day){diaryDate=day.dataset.diaryDay;diaryView='day';render();return;}const move=e.target.closest('[data-diary-move]');if(move){const n=Number(move.dataset.diaryMove);if(diaryView==='day')diaryDate=addDays(diaryDate,n);else if(diaryView==='week')diaryDate=addDays(diaryDate,n*7);else{const d=localDate(diaryDate);d.setMonth(d.getMonth()+n,1);diaryDate=dateISO(d);}render();return;}if(e.target.closest('[data-diary-today]')){diaryDate=todayISO();render();return;}const tag=e.target.closest('[data-diary-tag]');if(tag){diaryTag=tag.dataset.diaryTag;render();return;}const del=e.target.closest('[data-delete-diary]');if(del&&(await appModal.confirm('This action cannot be undone. Attached media belonging to this entry will also be deleted.',{title:'Delete diary entry?',confirmLabel:'Delete',destructive:true})).confirmed){const entry=state.diaryEntries.find(d=>d.id===del.dataset.deleteDiary);state.diaryEntries=state.diaryEntries.filter(d=>d.id!==entry.id);await saveState();await Promise.all((entry.media||[]).map(m=>deleteDiaryMedia(m.id).catch(()=>{})));location.hash='#diary';render();}});
window.GatheredDiaryTest={normalizeTags,getDiaryEventsForDate,addDays,dateISO,localDate};
